version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
        - "3000:3000"
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    networks:
      - aira-app
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    networks:
      - aira-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - aira-app
    volumes:
      - mongo-data:/data/db
networks:
  aira-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local